[theme]
# Cor primária: Verde Musgo do Ibama (usada em botões, links, seleções e destaques)
primaryColor = "#2A5C34"

# Cor de fundo principal da página: Branco Puro (para um visual limpo e claro)
backgroundColor = "#FFFFFF"

# Cor de fundo secundária: Creme/Cinza Claro Suave (usada na barra lateral e caixas)
secondaryBackgroundColor = "#F4F6F4"

# Cor do texto principal: Cinza Escuro quase preto (garante ótima acessibilidade e leitura)
textColor = "#2D312E"

# Fonte padrão do sistema
font = "sans serif"
